# Dockerfile.tools
FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends patchelf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
ENTRYPOINT ["/usr/bin/patchelf"]
